USE [master]
GO

/****** Object:  Database [GlobalTIBD]    Script Date: 09/07/2018 04:19:13 ******/
CREATE DATABASE [GlobalTIBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GlobalTIBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\GlobalTIBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GlobalTIBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\GlobalTIBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [GlobalTIBD] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GlobalTIBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [GlobalTIBD] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [GlobalTIBD] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [GlobalTIBD] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [GlobalTIBD] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [GlobalTIBD] SET ARITHABORT OFF 
GO

ALTER DATABASE [GlobalTIBD] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [GlobalTIBD] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [GlobalTIBD] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [GlobalTIBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [GlobalTIBD] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [GlobalTIBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [GlobalTIBD] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [GlobalTIBD] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [GlobalTIBD] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [GlobalTIBD] SET  DISABLE_BROKER 
GO

ALTER DATABASE [GlobalTIBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [GlobalTIBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [GlobalTIBD] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [GlobalTIBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [GlobalTIBD] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [GlobalTIBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [GlobalTIBD] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [GlobalTIBD] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [GlobalTIBD] SET  MULTI_USER 
GO

ALTER DATABASE [GlobalTIBD] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [GlobalTIBD] SET DB_CHAINING OFF 
GO

ALTER DATABASE [GlobalTIBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [GlobalTIBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [GlobalTIBD] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [GlobalTIBD] SET QUERY_STORE = OFF
GO

USE [GlobalTIBD]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [GlobalTIBD] SET  READ_WRITE 
GO

USE [GlobalTIBD]
GO

/****** Object:  Table [dbo].[Usuarios]    Script Date: 09/07/2018 04:22:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuarios](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[Senha] [varchar](20) NOT NULL,
	[Nome] [varchar](20) NOT NULL,
	[Latitude] [numeric](18, 2) NULL,
	[Longitude] [numeric](18, 2) NULL
) ON [PRIMARY]
GO




